export default {
  group: 'Custodian Group',
  custodianGroupRequired: 'Custodian group is a required field',
  pleaseSelect: '-- Please select ---',
  applicationNameRequired: 'Application name is a required field.',
  applicationNameLength: 'Application name must not be more than 255 characters.',
  applicationAlphaNumeric: 'Application name must only have alphabetical and numerical characters',
  applicationName: 'Application Name',
  cmdbId: 'CMDBId',
  cmdbIdRequired: 'CmdbId is a required field.',
  cmdbIdLength: 'CMDBId must not be more than 50 characters.',
  cmdbIdAlphaNumeric: 'CMDBId must be alphanumeric.',
  owner: 'Owner',
  ownerRequired: 'Owner is a required field',
  ownerLength: 'Owner must not be more than 255 characters.',
  ownerAlpha: 'Owner must contain alphabets.',
  description: 'Description',
  descriptionLength: 'Description must not be more than 255 characters.',
  descriptionRequired: 'Description is a required field.',
  descriptionAlphaNumeric: 'Description must only have alphabetical and numerical characters',
  descriptionInvalidCharacters: 'Description contains invalid characters.',
  createApplication: 'Create Application',
};
